# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'DFresh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DFresh
  pod 'SwiftX', :path => '../../', :subspecs => [
    'Globals',
    'Cache',
    # 'OpenSDK'
  ]

  pod 'FBusiness', :path => '../', :subspecs => [
    'Base',
    'DConfig',
    'DLogin',
    'DHome',
  ]

  target 'DFreshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DFreshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "#{target.name}"
        if ['Toaster'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
        else
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
        end
        
        if target.name == 'FBusiness'
          target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','FRESH_DELIVERY=1']
          end
        end
    end
end
